package dto

var EnMsg = map[int]string{
	SUCCESS:                             "success",
	PARAM_ERROR:                         "param error",
	NETWORK_ERROR:                       "network error",
	UNAUTHORIZED_ERROR:                  "unauthorized",
	NEED_CONTACT_INFO:                   "need contact info",
	ORGANIZATION_CERTIFICATION_REQUIRED: "organization certification required",
	HAVE_TAKE_TASK:                      "have take task",
	FILL_TOO_LARGE:                      "file too large",
	TOO_OFTEN:                           "too often",
	FILL_TOO_MANY:                       "file too many",
	CAPTCHA_ERROR:                       "captcha error",
	INVITATION_CODE_ERROR:               "invitation code error",
	HAVE_REGISTERED:                     "have registered",
	EMAIL_ERROR:                         "email error",
	ACCOUNT_PASSWORD_ERROR:              "account or password error",
	NO_VIP:                              "not vip",
	NO_TRADERBOT:                        "no trader bot id",
	NO_ACCOUNT:                          "no account",
	NO_USER:                             "no user",
	INSUFFICIENT_BALANCE:                "Insufficient balance",
	EXIST_UNSETTLED_ORDER:               "Exist unsettled order",
	MINIMUM_AMOUNT_ERROR:                "Minimum top up of 50",
	INVALID_ACCOUNT:                     "Invalid account",
	ORDER_FAIL:                          "Order failed",
	SYMBOL_CONFIG_EXISTS:                "Symbol config exists",
	EXISTS:                              "exists",
	SYMBOL_CONFIG_NO_EXISTS:             "Symbol config no exists",
	HOST_ID_ERROR:                       "Host id error",
	MARKET_ACCOUNT_ID_ERROR:             "Market account id error",
	HEDGE_ACCOUNT_ID_ERROR:              "Hedge account id error",
	NO_EXISTS:                           "no exists",
}
